name: "Docker compose autodiscovery using git scm"
scms:
  default:
    kind: git
    spec:
      url: https://github.com/updatecli/updatemonitor.git
    
autodiscovery:
  # scmid is applied to all crawlers
  scmid: default
  crawlers:
    dockercompose:
      ignore: 
       - path: "*/docker-compose.yaml"
         services:
          -  traefik
      #only:
      #  # - path: <filepath relative to scm repository>
      #  # - path: chart/*
#
