---
name-template: "v$RESOLVED_VERSION 🌈"
tag-template: "v$RESOLVED_VERSION"
categories:
  - title: "🚀 Features"
    labels:
      - "feature"
      - "enhancement"
  - title: "🐛 Bug Fixes"
    labels:
      - "fix"
      - "bugfix"
      - "bug"
  - title: "🧰 Maintenance"
    labels:
      - "chore"
      - "dependencies"
      - "cleanup"
      - "deprecated"
      - "depreciation"
  - title: "📝 Documentation"
    labels:
      - "documentation"
      - "doc"
      - "docs"
change-template: "- $TITLE @$AUTHOR (#$NUMBER)"

template: |
  ## Changes

  $CHANGES

  ## Contributors

  $CONTRIBUTORS

  ## Sponsors

  If Updatecli is useful to you, please consider sponsoring it.  
  Your support helps maintain and improve this project.

  [![GitHub stars](https://img.shields.io/github/stars/updatecli/updatecli?style=for-the-badge)](https://github.com/updatecli/updatecli/stargazers) [![Sponsor](https://img.shields.io/badge/Sponsor-%E2%9D%A4-pink?style=for-the-badge)](https://www.updatecli.io/support/#sponsor-or-donate)

version-resolver:
  major:
    labels:
      - "major"
      - "breaking"
  minor:
    labels:
      - "minor"
      - "feature"
      - "enhancement"
  patch:
    labels:
      - "patch"
      - "fix"
      - "bugfix"
      - "bug"
      - "chore"
      - "dependencies"
      - "documentation"
      - "doc"
      - "docs"
      - "cleanup"
      - "deprecated"
      - "depreciation"
  default: patch
exclude-labels:
  - "skip-changelog"
