source:
  name: "Get docker image digest for olblak/polls:latest"
  kind: dockerDigest
  spec:
    image: "olblak/polls"
    tag: "latest"
targets:
  imageTag:
    name: "updatecli docker image tag"
    kind: "yaml"
    prefix: "olblak/polls@256:"
    spec:
      #path: "/tt"
      #file: "/home/olblak/Project/Jenkins-infra/polls/docker-compose.yaml"
      file: "../../Jenkins-infra/polls/docker-compose.yamli"
      #file: "docker-compose.yamli"
      key: "services.api.image"
