sources:
  lastHelmRelease:
    kind: "helmchart"
    spec:
      name: "prometheus"
      url: "https://prometheus-community.github.io/helm-charts"

conditions:
  isNamePrometheus:
    kind: "yaml"
    spec:
      file: "helmfile.d/prometheus.yaml"
      key: "releases[0].name"
      value: "prometheus"
    scmid: "default"

targets:
  chartVersion:
    name: "Update Prometheus Helm Chart version"
    kind: "yaml"
    spec:
      file: "helmfile.d/prometheus.yaml"
      key: "releases[0].version"
    scmid: "default"

scms:
  default: 
    kind: "github"
    spec:
      user: '{{ .github.user }}'
      email: '{{ .github.email }}'
      owner: '{{ .github.owner }}'
      repository: '{{ .github.repository }}'
      token: '{{ requiredEnv .github.token }}'
      username: '{{ .github.username }}'
      branch: '{{ .github.branch }}'
