version: "2"
linters:
  default: none
  enable:
    - asciicheck
    - depguard
    - dogsled
    - errcheck
    - funlen
    - goconst
    - goprintffuncname
    - gosec
    - ineffassign
    - misspell
    - nakedret
    - nolintlint
    - rowserrcheck
    - staticcheck
    - unconvert
    - unparam
    - unused
  settings:
    depguard:
      rules:
        main:
          deny:
            - pkg: github.com/alecthomas/assert
              desc: not allowed
            - pkg: github.com/magiconair/properties/assert
              desc: not allowed
    dupl:
      threshold: 100
    exhaustive:
      default-signifies-exhaustive: false
    funlen:
      lines: 200
      statements: 150
    goconst:
      min-len: 3
      min-occurrences: 3
    gocritic:
      disabled-checks:
        - dupImport
        - ifElseChain
        - octalLiteral
        - whyNoLint
        - wrapperFunc
      enabled-tags:
        - diagnostic
        - experimental
        - opinionated
        - performance
        - style
    gocyclo:
      min-complexity: 15
    govet:
      enable-all: true
      settings:
        shadow:
          strict: true
    lll:
      line-length: 140
    misspell:
      locale: US
    nolintlint:
      require-explanation: false
      require-specific: false
      allow-unused: false
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - funlen
          - mnd
        path: _test\.go
      - linters:
          - testpackage
        path: _expansion_test\.go
      - linters:
          - gocritic
        text: 'unnecessaryDefer:'
    paths:
      - test/testdata_etc
      - internal/cache
      - internal/renameio
      - internal/robustio
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gofmt
    - goimports
  exclusions:
    generated: lax
    paths:
      - test/testdata_etc
      - internal/cache
      - internal/renameio
      - internal/robustio
      - third_party$
      - builtin$
      - examples$
