---
archives:
  - name_template: '{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}'
    replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      amd64: x86_64
    format_overrides:
      - goos: windows
        format: zip
    files:
      - README.adoc
      - LICENSE

before:
  hooks:
##    - go mod tidy
    - go mod download

builds:
  - id: updatecli
    main: ./main.go
    binary: updatecli
    ldflags:
      - -w -s
      - -X "github.com/updatecli/updatecli/pkg/core/version.BuildTime={{.Date}}"
      - -X "github.com/updatecli/updatecli/pkg/core/version.GoVersion={{.Env.GOVERSION}}"
      - -X "github.com/updatecli/updatecli/pkg/core/version.Version={{ .Version }}"
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
      - arm

changelog:
  ## Delegate Changelog to release-drafter
  skip: true

dockers:
  - image_templates:
      - 'updatecli/updatecli:{{ .Tag }}-amd64'
      - 'ghcr.io/updatecli/updatecli:{{ .Tag }}-amd64'
    dockerfile: Dockerfile
    use: buildx
    build_flag_templates:
      - "--pull"
      - "--no-cache"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.name={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
      - "--label=org.opencontainers.image.source={{.GitURL}}"
      - "--platform=linux/amd64"
    goos: linux
    goarch: amd64
    extra_files:
      - Makefile
  - image_templates:
      - 'updatecli/updatecli:{{ .Tag }}-arm64'
      - 'ghcr.io/updatecli/updatecli:{{ .Tag }}-arm64'
    dockerfile: Dockerfile
    use: buildx
    build_flag_templates:
      - "--pull"
      - "--no-cache"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.name={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
      - "--label=org.opencontainers.image.source={{.GitURL}}"
      - "--platform=linux/arm64"
    goos: linux
    goarch: arm64
    extra_files:
      - Makefile

docker_manifests:
  - name_template: 'updatecli/updatecli:{{ .Tag }}'
    image_templates:
      - 'updatecli/updatecli:{{ .Tag }}-amd64'
      - 'updatecli/updatecli:{{ .Tag }}-arm64'
  - name_template: 'ghcr.io/updatecli/updatecli:{{ .Tag }}'
    image_templates:
      - 'ghcr.io/updatecli/updatecli:{{ .Tag }}-amd64'
      - 'ghcr.io/updatecli/updatecli:{{ .Tag }}-arm64'
  - name_template: 'updatecli/updatecli:latest'
    image_templates:
      - 'updatecli/updatecli:{{ .Tag }}-amd64'
      - 'updatecli/updatecli:{{ .Tag }}-arm64'
  - name_template: 'ghcr.io/updatecli/updatecli:latest'
    image_templates:
      - 'ghcr.io/updatecli/updatecli:{{ .Tag }}-amd64'
      - 'ghcr.io/updatecli/updatecli:{{ .Tag }}-arm64'

env:
  - GO111MODULE=on
  - CGO_ENABLED=0

nfpms:
  - file_name_template: '{{ .ProjectName }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}'
    homepage: 'https://www.updatecli.io'
    description: 'Updatecli is a tool used to define and apply file update strategies.'
    maintainer: 'Olivier Vernin <olivier@vernin.me>'
    license: 'MIT'
    vendor: Updatecli
    formats:
      - apk
      - deb
      - rpm
    dependencies:
      - ca-certificates

snapshot:
  name_template: "{{ .Tag }}-next"

brews:
  - name: updatecli
    folder: Formula
    tap:
      owner: updatecli
      name: homebrew-updatecli
      token: "{{ .Env.HOMEBREW_TAP_GITHUB_TOKEN }}"
    commit_msg_template: "Brew formula update for {{ .ProjectName }} version {{ .Tag }}"
    homepage: "https://updatecli.io/"
    description: "Continuously update everything."
    license: "MIT"
    test: |
      system "#{bin}/updatecli version"
