---
env:
  - GO111MODULE=on
  - CGO_ENABLED=0

build:
  goos:
    - linux
    - windows
    - darwin

  goarch:
    - amd64
    - arm64
    - arm
  goarm:
    - 6
    - 7
  ignore:
    - goos: linux
      goarch: arm
      goarm: 7

before:
  hooks:
    - go mod download

builds:
  - id: updatecli
    main: ./main.go
    binary: updatecli
    ldflags:
      - -w -s
      - -X "github.com/olblak/updateCli/pkg/core/version.BuildTime={{.Date}}"
      - -X "github.com/olblak/updateCli/pkg/core/version.GoVersion={{.Env.GOVERSION}}"
      - -X "github.com/olblak/updateCli/pkg/core/version.Version={{ .Version }}"
    goos:
      - linux
      - darwin # i386 not supported anymore https://github.com/golang/go/issues/37610
      - windows
    goarch:
      - "amd64"

archives:
  - replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      amd64: x86_64

snapshot:
  name_template: "{{ .Tag }}-next"

release:
  github:
    owner: updatecli
    name: updatecli
  draft: true
changelog:
  ## Delegate Changelog to release-drafter
  skip: true
...
