[files]
extend-exclude = [
  "go.mod",
  "go.sum",
  "go.1.mod",
  "vale",
  "_typos.toml",
  "e2e/updatecli.d/invalid.d/typos.yaml",
  "pkg/core/config/schemavalidate_test.go",
  "pkg/core/jsonschema/validate.go",
  "pkg/core/jsonschema/compile_test.go",
  "pkg/core/compose/schemavalidate_test.go",
]

[default]
extend-ignore-re = ["lQOs.*", "lIYEY.*", "mDMEYi.*", "WRONLY", "nce", "Gti"]

[default.extend-words]
# Don't correct the surname "Teh"
lQOsBGIqZEEBCACOnlRGd40w2SvqxFe0FRtBhruQIHLWpWAkYxz6otNRuCAkK7w1 = "lQOsBGIqZEEBCACOnlRGd40w2SvqxFe0FRtBhruQIHLWpWAkYxz6otNRuCAkK7w1"
hom = "hom"
