= CONTRIBUTING
:toc: preamble
:toclevels: 3

Thanks for your interest in this project, feel free to ask any questions you may have.

== REQUIREMENTS

To build the project, just ensure to have access to the correct golang version then just run `make build` which should return something like:

```
echo v0.0.15-6-g1e24f1d
v0.0.15-6-g1e24f1d
go build \
	-ldflags "-w -s \
        -X \"github.com/updatecli/updatecli/pkg/version.BuildTime=`date -R`\" \
        -X \"github.com/updatecli/updatecli/pkg/version.GoVersion=go version go1.16.2 linux/amd64\" \
        -X \"github.com/updatecli/updatecli/pkg/version.Version=v0.0.15-6-g1e24f1d\""\
        -o bin/updatecli
```

or using docker

```
docker run --rm -v "$PWD":/usr/src/updatecli -w /usr/src/updatecli -e GOOS=windows -e GOARCH=386 golang:1.16 go build -v
```

== CONTRIBUTE

They are multiple ways to contribute which don't necessarily involve coding like providing feedback, improving documentation, processes.
Here I'll just highlight some of them

=== FEEDBACK

It significantly harder to build a solution that could be used by different people. It involves many different skills that are hard to master and it's easy to get stuck in local optimum. So feel free to reach out to say what's wrong and what could be improved.

=== CODE

The code is divided into two categories, core, and plugins. It says what it says. The core is designed to be independent and to provide the skeleton for the application while the plugins define how things are automated for a specific use-case. The easiest part is probably plugins as it allows you to contribute independently to the process you are looking to automate.

==== CORE

This section is still evolving as they are many areas that need attention.

==== PLUGINS

Plugins can be easily added following this workflow:

===== 1. Define Package name

Creating a new directory using your "packageName" under the directory `pkg/plugins` that will contain your go package similar to:

```
pkg
├── plugins
│   └── packageName
│       ├── source_test.go
│       ├── source.go
│       ├── condition_test.go
│       ├── condition.go
│       ├── target_test.go
│       ├── target.go
│       ├── main_test.go
│       └── main.go
└── main_test.go

```

===== 2. Define configuration

In the `main.go`, you need to define the `struct` that you'll use to configure your workflow where the capitalized fields will be set when unmarshalling from your future configuration.yaml

```
type Capitalized_package_name struct {
	Field1        string
	Field2        string 
	Field3        string
	Field4        string
}
```

===== 3. Respect the contract

Your 'packageName' must respect at least one of the following interface contract by defining appropriated functions.

[cols="1,2a,2", options="header"]
.Rules
|===
| Stage
| Interface
| Description

| Source
| ```
type Spec interface {
    Source() (string, error)
}
```
| Defines how a version will be retrieved then passed the following stages

| Changelog
| ```
type Changelog interface {
    Changelog(release string) (string, error)
}
```
| Retrieve the changelog for a specific source.

| Condition
| ```
type Spec interface {
    Condition(version string) (bool, error)
    ConditionFromSCM(version string, scm scm.Scm) (bool, error)
}
```
| Define a condition which has to pass in order to proceed

| Target
| ```
type Spec interface {
    Target(source string, dryRun bool) (bool, error)
    TargetFromSCM(source string, scm scm.Scm, dryRun bool) (changed bool, files []string, message string, err error)

```
| Define how a target file will be updated

|===

===== 4. Claim your name

Each stage which can be configured using a yaml/go template has to bind a resource kind and a package name, this is done in the "Unmarshal" function

```
  import "github.com/updatecli/updatecli/pkg/plugins/packageName"
  ...

	case "packageName":
		p := packageName.PackageName{}
		err := mapstructure.Decode(s.Spec, &p)

		if err != nil {
			return err
		}

		spec = &p
```

Now something like this, should be working:

config.value
```
# updatecli diff --config config.value

source:
  kind: packageName
  spec:
    field1: "value"
    field3: "value"
targets:
  idName:
    name: "updatecli"
    kind: "yaml"
    prefix: "olblak/polls@256:"
    spec:
      file: "..."
      key:  "..."
```


=== DOCUMENTATION

If you spot phrasing issues or just a lack of documentation, feel free to open an issue and/or a pull request with your contribution.
https://github.com/updatecli/website[website]
