policies:
  - name: Local Updatecli Policies
    config:
      - updatecli/updatecli.d/
    values:
      - updatecli/values.d/scm.yaml
  - name: Update Updatecli policies
    policy: ghcr.io/updatecli/policies/updatecli/autodiscovery:0.8.1@sha256:f8edda1a6cbf0d7274e2b847ede29fc4dc70dd5302ccb8575ae21b069cc0d8a0
    values:
      - updatecli/values.d/scm.yaml
      - updatecli/values.d/updatecli-compose.yaml
  - name: Golang Version
    policy: ghcr.io/updatecli/policies/golang/version:0.7.1@sha256:b8590dff076dbd81ac160351e4749142f94a9ea718cc18c3c56c126067a29607
    values:
      - updatecli/values.d/scm.yaml
  - name: Major Golang Module update
    policy: ghcr.io/updatecli/policies/autodiscovery/golang:0.13.1@sha256:85a008b9760fc02b05f68f4047d53b7c05f7250d5a8e8e7da33e925c72c885e0
    values:
      - updatecli/values.d/scm.yaml
      - updatecli/values.d/golang_major.yaml
  - name: Minor Golang Module update
    policy: ghcr.io/updatecli/policies/autodiscovery/golang:0.13.1@sha256:85a008b9760fc02b05f68f4047d53b7c05f7250d5a8e8e7da33e925c72c885e0
    values:
      - updatecli/values.d/scm.yaml
      - updatecli/values.d/golang_minor.yaml
  - name: Patch Golang Module update
    policy: ghcr.io/updatecli/policies/autodiscovery/golang:0.13.1@sha256:85a008b9760fc02b05f68f4047d53b7c05f7250d5a8e8e7da33e925c72c885e0
    values:
      - updatecli/values.d/scm.yaml
      - updatecli/values.d/golang_patch.yaml
  - name: Update golangci-lint
    policy: ghcr.io/updatecli/policies/golangci-lint/githubaction:0.8.1@sha256:7fb34ae17a84641f02c3ff2aa0f8156a7108f32f21282b0070b8883c86ba6e67
    values:
      - updatecli/values.d/scm.yaml
  - name: Update githubactions
    policy: ghcr.io/updatecli/policies/autodiscovery/githubaction:0.4.1@sha256:869b676074f9fee7edd5d488140a12c3b09a5f8a175f12f26ea85a4f8bd0a9d1
    values:
      - updatecli/values.d/scm.yaml
      - updatecli/values.d/githubaction.yaml
