package npm

import (
	"os"
	"testing"

	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
)

type lockedVersionTest struct {
	name       string
	constraint string
	expected   string
}

func assertLockedVersions(t *testing.T, versions lockedVersions, tests []lockedVersionTest) {
	t.Helper()

	for _, tt := range tests {
		assert.Equal(t, tt.expected, versions.version(tt.name, tt.constraint), "%s@%s", tt.name, tt.constraint)
	}
}

func TestParsePackageLock(t *testing.T) {
	t.Run("lockfileVersion 3 from testdata", func(t *testing.T) {
		data, err := os.ReadFile("testdata/npmlockfile/package-lock.json")
		require.NoError(t, err)

		versions, err := parsePackageLock(data)
		require.NoError(t, err)

		assertLockedVersions(t, versions, []lockedVersionTest{
			{name: "axios", constraint: "^1.0.0", expected: "1.2.6"},
			{name: "unknown", constraint: "^1.0.0", expected: ""},
		})
	})

	t.Run("lockfileVersion 3 ignores nested packages", func(t *testing.T) {
		versions, err := parsePackageLock([]byte(`{
  "lockfileVersion": 3,
  "packages": {
    "": {"name": "project"},
    "node_modules/@mdi/font": {"version": "5.9.55"},
    "node_modules/axios": {"version": "1.2.6"},
    "node_modules/axios/node_modules/follow-redirects": {"version": "1.14.0"},
    "packages/workspace": {"version": "0.1.0"}
  }
}`))
		require.NoError(t, err)

		assertLockedVersions(t, versions, []lockedVersionTest{
			{name: "@mdi/font", constraint: "^5.0.0", expected: "5.9.55"},
			{name: "axios", constraint: "*", expected: "1.2.6"},
			{name: "follow-redirects", constraint: "^1.0.0", expected: ""},
		})
	})

	t.Run("lockfileVersion 1", func(t *testing.T) {
		versions, err := parsePackageLock([]byte(`{
  "lockfileVersion": 1,
  "dependencies": {
    "axios": {
      "version": "0.21.1",
      "dependencies": {"follow-redirects": {"version": "1.14.0"}}
    }
  }
}`))
		require.NoError(t, err)

		assertLockedVersions(t, versions, []lockedVersionTest{
			{name: "axios", constraint: "^0.21.0", expected: "0.21.1"},
			{name: "follow-redirects", constraint: "^1.0.0", expected: ""},
		})
	})

	t.Run("Invalid file", func(t *testing.T) {
		_, err := parsePackageLock([]byte(`{`))
		require.Error(t, err)
	})
}

func TestParsePnpmLock(t *testing.T) {
	t.Run("lockfileVersion 9 from testdata", func(t *testing.T) {
		data, err := os.ReadFile("testdata/pnpmlockfile/pnpm-lock.yaml")
		require.NoError(t, err)

		versions, err := parsePnpmLock(data)
		require.NoError(t, err)

		assertLockedVersions(t, versions, []lockedVersionTest{
			{name: "@mdi/font", constraint: "5.9.55", expected: "5.9.55"},
		})
	})

	t.Run("lockfileVersion 9 ignores other workspace projects", func(t *testing.T) {
		versions, err := parsePnpmLock([]byte(`lockfileVersion: '9.0'
importers:
  .:
    devDependencies:
      typescript:
        specifier: ^5.0.0
        version: 5.1.6
  packages/app:
    dependencies:
      react:
        specifier: ^17.0.0
        version: 17.0.2
`))
		require.NoError(t, err)

		assertLockedVersions(t, versions, []lockedVersionTest{
			{name: "typescript", constraint: "^5.0.0", expected: "5.1.6"},
			{name: "react", constraint: "^17.0.0", expected: ""},
		})
	})

	t.Run("lockfileVersion 6 with peer dependencies", func(t *testing.T) {
		versions, err := parsePnpmLock([]byte(`lockfileVersion: '6.0'
dependencies:
  react-dom:
    specifier: ^18.0.0
    version: 18.2.0(react@18.2.0)
devDependencies:
  typescript:
    specifier: ^5.0.0
    version: 5.1.6
`))
		require.NoError(t, err)

		assertLockedVersions(t, versions, []lockedVersionTest{
			{name: "react-dom", constraint: "^18.0.0", expected: "18.2.0"},
			{name: "typescript", constraint: "^5.0.0", expected: "5.1.6"},
		})
	})

	t.Run("lockfileVersion 5", func(t *testing.T) {
		versions, err := parsePnpmLock([]byte(`lockfileVersion: 5.4
specifiers:
  axios: ^1.0.0
dependencies:
  axios: 1.2.6_debug@4.3.4
`))
		require.NoError(t, err)

		assertLockedVersions(t, versions, []lockedVersionTest{
			{name: "axios", constraint: "^1.0.0", expected: "1.2.6"},
		})
	})
}

func TestParseYarnLock(t *testing.T) {
	expected := []lockedVersionTest{
		{name: "@mdi/font", constraint: "5.9.55", expected: "5.9.55"},
		{name: "axios", constraint: "^1.0.0", expected: "1.2.6"},
		{name: "axios", constraint: "^1.1.0", expected: "1.2.6"},
		{name: "axios", constraint: "^2.0.0", expected: ""},
		{name: "follow-redirects", constraint: "^1.15.0", expected: "1.15.2"},
	}

	t.Run("Yarn classic", func(t *testing.T) {
		versions, err := parseYarnLock([]byte(`# THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
# yarn lockfile v1


"@mdi/font@5.9.55":
  version "5.9.55"
  resolved "https://registry.yarnpkg.com/@mdi/font/-/font-5.9.55.tgz"

axios@^1.0.0, axios@^1.1.0:
  version "1.2.6"
  resolved "https://registry.yarnpkg.com/axios/-/axios-1.2.6.tgz"
  dependencies:
    follow-redirects "^1.15.0"
    version "9.9.9"

follow-redirects@^1.15.0:
  version "1.15.2"
`))
		require.NoError(t, err)

		assertLockedVersions(t, versions, expected)
	})

	t.Run("Yarn berry", func(t *testing.T) {
		versions, err := parseYarnLock([]byte("__metadata:\r\n" +
			"  version: 6\r\n" +
			"  cacheKey: 8\r\n" +
			"\r\n" +
			"\"@mdi/font@npm:5.9.55\":\r\n" +
			"  version: 5.9.55\r\n" +
			"  resolution: \"@mdi/font@npm:5.9.55\"\r\n" +
			"\r\n" +
			"\"axios@npm:^1.0.0, axios@npm:^1.1.0\":\r\n" +
			"  version: 1.2.6\r\n" +
			"  dependencies:\r\n" +
			"    follow-redirects: ^1.15.0\r\n" +
			"\r\n" +
			"\"follow-redirects@npm:^1.15.0\":\r\n" +
			"  version: 1.15.2\r\n"))
		require.NoError(t, err)

		assertLockedVersions(t, versions, expected)
	})
}

func TestNormalizeYarnDescriptor(t *testing.T) {
	for descriptor, expected := range map[string]string{
		"":                     "",
		"__metadata":           "__metadata",
		"axios@^1.0.0":         "axios@^1.0.0",
		"axios@npm:^1.0.0":     "axios@^1.0.0",
		"@mdi/font@5.9.55":     "@mdi/font@5.9.55",
		"@mdi/font@npm:5.9.55": "@mdi/font@5.9.55",
	} {
		assert.Equal(t, expected, normalizeYarnDescriptor(descriptor), descriptor)
	}
}
