= Documentation
:toc: preamble
:toclevels: 3


Updatecli is a tool to define and apply file update strategy.

It reads its configuration from a yaml or go template configuration file, then works into three stages

1. Source: Based on a rule, updatecli fetches a value that will be injected in later stages
2. Conditions: Ensure that conditions are met based on the value retrieved during the source rule
3. Target: Update and publish the target files based on a value retrieved from the source stage.

== Installation
Updatecli is available https://github.com/olblak/updatecli/releases/latest[here] (Windows, Linux, OSX).

A docker image is also available on https://hub.docker.com/r/olblak/updatecli[Dockerhub] or https://github.com/users/olblak/packages/container/package/updatecli[Ghcr]

== Usage

'updateCli' is a tool that updates files according to a custom update strategy definition. Once your strategy has been defined, just call one of the following:

Using a yaml strategy
```
updatecli diff --config strategy.yaml
updatecli apply --config strategy.yaml
updatecli help
```

Using a go template strategy
```
updatecli diff --config strategy.tpl --values values.yaml
updatecli apply --config strategy.tpl --values values.yaml
updatecli help
```

Using a docker image

```
 docker run -i -t -v "$PWD/updateCli.yaml":/updatecli/updateCli.yaml:ro olblak/updatecli:v0.0.21 diff --config /updatecli/updateCli.yaml

 docker run -i -t -v "$PWD/updateCli.yaml":/updatecli/updateCli.yaml:ro olblak/updatecli:v0.0.21 apply --config /updatecli/updateCli.yaml

 docker run -i -t olblak/updatecli:v0.0.21 help
```

== Strategy

A strategy defines how to update a target file and it describes three stages

1. Source: Based on a rule fetch a value that will be injected in later stages
2. Conditions: Ensure that conditions are met based on the value retrieved during the source rule
3. Target: Update and publish the target files based on a value retrieved from the source stage.

.strategy.yaml
```
source:
  kind: <sourceType>
  spec:
    <sourceTypeSpec>>
conditions:
  conditionID:
    kind: <conditionType>
    spec:
      <conditionTypeSpec>
targets:
  target1:
    kind: <targetType>
    spec:
      <targetTypeSpec>
```

**YAML**

Accepted extensions: ".yaml",".yml"

A YAML configuration can be specified using `--config <yaml_file>`, it accepts either a single file or a directory, if a directory is specified, then it runs recursively on every file inside the directory.

**Go Templates**

Accepted extensions: ".tpl",".tmpl"

Another way to use this tool is by using go template files in place of YAML.
Using go templates allow us to specify generic values in a different yaml file then reference those values from each go templates.
We also provide a custom function called requireEnv to inject any environment variable in the template example, `{{ requiredEnv "PATH" }}`.

The strategy file can either be using a yaml format or a golang template.

=== Source

==== Github Release

This source will get a release version from Github Release api. If "latest" is specified, it retrieves the version referenced by 'latest'.

.Example
```
source:
  kind: githubRelease
  spec:
    owner: "Github Owner"
    repository: "Github Repository"
    token: "Don't commit your secrets!"
    url: "Github Url"
    version: "Version to fetch"
```

**A configuration using go template can be used to retrieve the environment variable instead of writing secrets in files, cfr later.**

==== Dockerfile
A Dockerfile retrieves information from a Dockerfile. To identify which information to retrieve, it uses the field "Instruction" with a custom syntax, `INSTRUCTION[x][y]`.

* `INSTRUCTION` must be replaced by any valid Dockerfile instruction like `ARG`, `ENV`, `LABEL`, etc
* "x", reference a specific instruction position where x is replaced by any integer starting from 0. So "0" means the first instruction of type `INSTRUCTION`, "1" means the second, etc
* "y", reference a specific argument element for the `INSTRUCTION[x]` where "y" is replaced by any integer starting from 0. So "0" means the first argument, "1" means the second, etc

The library uses to manipulate Dockerfile, split each INSTRUCTION into arrays so the line
`LABEL key1=value2 key2=value2` becomes `["key1","value2","key2","value2"]`

* `LABEL[0][0]` equal `key1`
* `LABEL[0][1]` equal `value2`
* `LABEL[0][3]` equal `key2`
* `LABEL[0][4]` equal `value2`

NOTE: A shorter syntax is available where `INSTRUCTION` is an alias for `INSTRUCTION[0][0]`.
For instance, based on the previous example, `LABEL` means "key1"

```
source:
  kind: dockerfile
  spec:
    file: docker/Dockerfile
    Instruction: ENV[0][0] #Long Syntax
    Instruction: ENV       #Short Syntax
#    Value: "HELM_VERSION"

```

==== DockerRegistry

This source will get a docker image tag from a docker registry and return its digest, so we can always reference a specific image tag like `latest`.

```
source:
  kind: dockerDigest
  spec:
    architecture: "Default to amd64, it's used when the same tag can reference different architecture like amd64 and arm64"
    image: "Docker Image"
    tag: "Docker Image Tag to fetch the checksum"
    token: "Token required for private repository"
```

Token value depends on the Docker registry and it can be retrieved in different ways:

* GHCR - Github uses personal access token as explained https://docs.github.com/en/free-pro-team@latest/github/authenticating-to-github/creating-a-personal-access-token[here]
* DockerHub - To retrieve a dockerhub token, it's easier to run `docker login` and then retriev the token stored in '~/.docker/config.json'

.~/.docker/config.json
```
        "auths": {
                "https://index.docker.io/v1/": {
                        "auth": "token"
                }
        },
```

Tested with Dockerhub, Ghcr.io

==== HelmChart
This source will get the latest helm chart version available.

```
source
  kind: helmChart
  spec:
    url: https://kubernetes-charts.storage.googleapis.com
    name: jenkins
```

==== Maven

This source will get the latest maven artifact version.

```
source:
  kind: maven
  spec:
    url:  "repo.jenkins-ci.org",
	repository: "releases",
	groupID:    "org.jenkins-ci.main",
	artifactID: "jenkins-war",
```

==== Replacer
A List of replacer rules can be provided to modify the value retrieved from source.

```
source:
  kind: githubRelease
  replaces:
    - from: "string"
      to: ""
    - from: "substring1"
      to: "substring2"
  spec:
    owner: "Github Owner"
    repository: "Github Repository"
    token: "Don't commit your secrets!"
    url: "Github Url"
    version: "Version to fetch"
```


==== Prefix/Postfix
A prefix and/or postfix can be added to any value retrieved from the source.
This prefix/postfix will be used by 'condition' checks, then by every target unless one is explicitly defined in a target.

.Example
```
source:
  kind: githubRelease
  prefix: "v"
  postfix: "-beta"
  spec:
    owner: "Github Owner"
    repository: "Github Repository"
    token: "Don't commit your secrets!"
    url: "Github Url"
    version: "Version to fetch"
```


=== Condition
During this stage, we check if conditions are met based on the value retrieved from the source stage otherwise we can skip the "target" stage.

==== Dockerfile
A Dockerfile validate information from a Dockerfile. It uses the field "Value" to define the expected value or if not defined, the field "Value" is set based on the source output. Then it uses the field "Instruction" to identify which information to validate using the custom syntax, `INSTRUCTION[x][y]`.

* `INSTRUCTION` must be replaced by any valid Dockerfile instruction like `ARG`, `ENV`, `LABEL`, etc
* "x", reference a specific instruction position where x is replaced by any integer starting from 0. So "0" means the first instruction of type `INSTRUCTION`, "1" means the second, etc
* "y", reference a specific argument element for the `INSTRUCTION[x]` where "y" is replaced by any integer starting from 0. So "0" means the first argument, "1" means the second, etc

The library uses to manipulate Dockerfile, split each INSTRUCTION into arrays so the line
`LABEL key1=value2 key2=value2` becomes `["key1","value2","key2","value2"]`

* `LABEL[0][0]` equal `key1`
* `LABEL[0][1]` equal `value2`
* `LABEL[0][3]` equal `key2`
* `LABEL[0][4]` equal `value2`

NOTE: A shorter syntax is available where `INSTRUCTION` is an alias for `INSTRUCTION[0][0]`.
For instance, based on the previous example, `LABEL` means "key1"

```
conditions:
  id:
    kind: dockerfile
    spec:
      file: docker/Dockerfile
      Instruction: ENV[0][0] #Long Syntax
      # Instruction: ENV       #Short Syntax
      Value: "HELM_VERSION"
      scm: #scm repository type", *optional
        #github:
        # or
        #git:

```
==== dockerImage

This condition checks if a docker image tag is available on a Docker Registry.

```
conditions:
  id:
    kind: dockerImage
    spec:
      architecture: "Default to amd64, it's used when the same tag can reference different architecture like amd64 and arm64"
      image: _Docker Image_
      tag: "Docker Image Tag to test, it overrides the value from source"
      token: "Token required for private repository"
```

Token value depends on the Docker registry and it can be retrieved in different ways:

* GHCR - Github uses personal access token as explained https://docs.github.com/en/free-pro-team@latest/github/authenticating-to-github/creating-a-personal-access-token[here]
* DockerHub - To retrieve the token, it's easier to run `docker login` and then retrieve the token stored in '~/.docker/config.json'

.~/.docker/config.json
```
        "auths": {
                "https://index.docker.io/v1/": {
                        "auth": "token"
                }
        },
```

Tested with Dockerhub, Ghcr.io

==== Maven
This condition checks if the source value is available on a maven repository

```
condition:
  kind: maven
  spec:
    url:  "repo.jenkins-ci.org",
	repository: "releases",
	groupID:    "org.jenkins-ci.main",
	artifactID: "jenkins-war",
```

==== HelmChart
This source checks if a helm chart exist, a version can also be specified

```
source
  kind: helmChart
  spec:
    url: https://kubernetes-charts.storage.googleapis.com
    name: jenkins
    version: 'x.y.x' (Optional)
```

==== yaml
Yaml key/value can be specified as condition in order to apply the target stage

```
conditions:
  uniqConditionName:
    name: "Test key/value presence"
    kind: yaml
    spec:
      file: "file.yaml"
      key: "key[0]"
      value:  "value"
    scm:
      ...
```

=== Targets

"Targets" stage will update the definition for every target based on the value returned during the source stage if all conditions are met.

==== Dockerfile

CAUTION: The targeted Dockerfile syntax won't be preserved and comments will be drop.

A Dockerfile target, updates a Dockerfile based on information retrieved from source. It uses the field "Value" to define the expected value or if not defined, the field "Value" is set based on the source output (which should be purpose anyway). Then it uses the field "Instruction" to identify which information to validate using the custom syntax, `INSTRUCTION[x][y]`.

* `INSTRUCTION` must be replaced by any valid Dockerfile instruction like `ARG`, `ENV`, `LABEL`, etc
* "x", reference a specific instruction position where x is replaced by any integer starting from 0. So "0" means the first instruction of type `INSTRUCTION`, "1" means the second, etc
* "y", reference a specific argument element for the `INSTRUCTION[x]` where "y" is replaced by any integer starting from 0. So "0" means the first argument, "1" means the second, etc

The library uses to manipulate Dockerfile, split each INSTRUCTION into arrays so the line
`LABEL key1=value2 key2=value2` becomes `["key1","value2","key2","value2"]`

* `LABEL[0][0]` equal `key1`
* `LABEL[0][1]` equal `value2`
* `LABEL[0][3]` equal `key2`
* `LABEL[0][4]` equal `value2`

NOTE: A shorter syntax is available where `INSTRUCTION` is an alias for `INSTRUCTION[0][0]`.
For instance, based on the previous example, `LABEL` means "key1"

TIP: It's a good idea to test that a LABEL key exist before updating its value


```
targets:
  taskId
    kind: dockerfile
    spec:
      file: docker/Dockerfile
      Instruction: ENV[0][1] #Long Syntax
    scm: #scm repository type", *optional
      #github:
      # or
      #git:

```

==== yaml

This target will update a yaml file base a value retrieve during the source stage.

```
targets:
  id:
    kind: yaml
    spec:
      file: "Yaml file path from the root repository"
      key: "yaml key to update"
    scm: #scm repository type"
      #github:
      # or
      #git:
```

NOTE: A key can either be string like 'key' or a position in an array like `array[0]` where 0 means the first element of `array`.
Keys and arrays can also be grouped with dot like `key.array[3].key`.

=== Misc
This category describe settings which can be use in any stages.

==== scm
Depending on the situation a specific scm block can be provided to the target and condition stage. At the moment it supports github and git.

===== git
Git push every change on the remote git repository

```
targets:
  id:
    kind: yaml
    spec:
      file: "Yaml file path from the root repository"
      key: "yaml key to update"
    scm:
      git:
        url: "git repository url"
        branch: "git branch to push changes"
        user: "git user to push from changes"
        email: "git user email to push from change"
        directory: "directory where to clone the git repository"
```

===== github
Github  push every change on a temporary branch then open a pull request

```
targets:
  id:
    kind: yaml
    spec:
      file: "Yaml file path from the root repository"
      key: "yaml key to update"
    scm:
      github:
        user: "git user to push from changes"
        email: "git user email to push from change"
        directory: "directory where to clone the git repository"
        owner: "github owner"
        repository: "github repository"
        token: "github token with enough permission on repository"
        username: "github username used for push git changes"
        branch: "git branch where to push changes"
```

==== Prefix/Postfix
A prefix and/or postfix can be added based on the value retrieved from the source.
This prefix/postfix won't be used by 'condition' checks. Any value specified at the target level override values defined in the source.

.Example
```
targets:
  imageTag:
    name: "Docker Image"
    kind: yaml
    prefix: "beta-"
    postfix: "-jdk11"
    spec:
      file: "charts/jenkins/values.yaml"
      key: "jenkins.controller.imageTag"
    scm:
      github:
        user: "updatecli"
        email: "updatecli@example.com"
        owner: "jenkins-infra"
        repository: "charts"
        token: {{ requiredEnv "GITHUB_TOKEN" }}
        username: "updatecli"
        branch: "main"
```

== Continuous Update
Updatecli is better when executed on a regular basis so let see how to use a CI environment for that.

=== Jenkins
As long as your Jenkins instance has the right credential to commit to your targeted repositories, you can use the following example

*Remark*: It assumes using Jenkins on kubernetes with the https://plugins.jenkins.io/kubernetes/[kubernetes-plugin]

.Jenkinsfile
```
pipeline {
  agent {
    kubernetes {
      label 'updatecli'
      yamlFile 'PodTemplates.yaml'
    }
  }
  environment {
    UPDATECLI_GITHUB_TOKEN  = credentials('updatecli-github-token')
  }

  triggers {
    cron 'H/30 * * * *'
  }

  stages {
    stage('Check Configuration Update') {
      steps {
        container('updatecli') {
          sh 'updatecli diff --config ./updateCli/updateCli.d --values ./updateCli/values.yaml'
        }
      }
    }
    stage('Apply Configuration Update') {
      steps {
        container('updatecli') {
          sh 'updatecli apply --config ./updateCli/updateCli.d --values ./updateCli/values.yaml'
        }
      }
    }
  }

```
.PodTemplates.yaml
```
apiVersion: "v1"
kind: "Pod"
metadata:
  labels:
    jenkins: "agent"
    job: "updatecli"
spec:
  containers:
  - args:
    - "99d"
    command:
    - "sleep"
    image: "olblak/updatecli:v0.0.21"
    imagePullPolicy: "Always"
    name: "updatecli"
    resources:
      limits:
        memory: "512Mi"
        cpu: "400m"
      requests:
        memory: "512Mi"
        cpu: "400m"
    securityContext:
      privileged: false
    tty: true
  restartPolicy: "Never"
```

=== Github Action

In case you are using Github Action, you can create a file with following content in the Github repository containing your updatecli strategies.

.updatecli/values.yaml
```
github:
  user: "GitHub Actions"
  email: "41898282+github-actions[bot]@users.noreply.github.com"
  username: "github-actions"
  token: "UPDATECLI_GITHUB_TOKEN"
```

..github/workflows/updatecli.yaml
```
name: Update CLI

on:
  workflow_dispatch:
  schedule:
    - cron: '0 9 * * 1'

jobs:
  update_cli:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Update CLI
        env:
          UPDATECLI_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          curl -sSfL -o updatecli https://github.com/olblak/updatecli/releases/latest/download/updatecli.linux.amd64
          chmod +x ./updatecli
          ./updatecli diff --config ./updateCli/updateCli.d --values ./updateCli/values.yaml
          ./updatecli apply --config ./updateCli/updateCli.d --values ./updateCli/values.yaml
```

== Examples

This project is currently used in the Jenkins Infrastructure project https://www.jenkins.io/projects/infrastructure/[link]

* https://github.com/jenkins-infra/charts/tree/master/updateCli/updateCli.d[UpdateCli configuration]
* https://github.com/jenkins-infra/charts/blob/master/Jenkinsfile_k8s#L35L48[Jenkinsfile]
* Results
** https://github.com/jenkins-infra/charts/pull/188[Docker Digest]
** https://github.com/jenkins-infra/charts/pull/179[Maven Repository]
** https://github.com/jenkins-infra/charts/pull/145[Github Release]
