github:
  user: "olblak"
  email: "updatecli@olblak.com"
  owner: "olblak"
  repository: "charts"
  #token: "UPDATECLI_GITHUB_TOKEN"
  token: "GITHUB_TOKEN"
  username: "olblak"
  branch: "mirror-rsync"
  admin: "asterix"
  #branch: "master"
  #branch: "azure-mirror"
