name: Test Flux Autodiscovery

scms:
  default:
    kind: git
    spec:
      url: https://github.com/updatecli-test/flux2-multi-tenancy.git

autodiscovery:
  # scmid is applied to all crawlers
  scmid: default
  crawlers:
    flux:
      # To ignore specific path
      ignore:
        - artifacts:
           "ghcr.io/kyverno/manifests/kyverno": ""
        # - path: <filepath relative to scm repository>
        # - path: chart/*
      #only:
      #  #- path: helmfile.d/*
      #  - artifacts:
      #      "ghcr.io/kyverno/manifests/kyverno": ""
      #  - repositories:
      #      - "https://charts.jetstack.io"
