name: "Docker compose autodiscovery using git scm"
scms:
  default:
    kind: git
    spec:
      url: https://github.com/jenkins-infra/evergreen.git
      branch: master
    
autodiscovery:
  # scmid is applied to all crawlers
  scmid: default
  crawlers:
    dockercompose:
