package gittag

import (
	"fmt"
	"strings"

	"github.com/go-viper/mapstructure/v2"
	"github.com/updatecli/updatecli/pkg/core/result"
	"github.com/updatecli/updatecli/pkg/plugins/scms/git"
	"github.com/updatecli/updatecli/pkg/plugins/utils/age"
	"github.com/updatecli/updatecli/pkg/plugins/utils/gitgeneric"
	"github.com/updatecli/updatecli/pkg/plugins/utils/redact"
	"github.com/updatecli/updatecli/pkg/plugins/utils/version"
)

/*
"gittag" defines the specification for manipulating Git tags.
It can be used as a "source", a "condition", or a "target".
*/
type Spec struct {
	// "path" defines the path of the local Git repository.
	//
	// compatible:
	//   * source
	//   * condition
	//   * target
	//
	// remark:
	//   * a relative path is resolved from the Updatecli manifest directory.
	//   * "path" overrides the working directory provided by the scm configuration.
	//   * "url" takes precedence over "path".
	//   * "path" cannot be used when "lsremote" is true.
	//
	Path string `yaml:",omitempty"`
	// "versionfilter" defines the version pattern and its type, such as regex, semver, or latest.
	//
	// compatible:
	//   * source
	//   * condition
	//   * target
	//
	// remark:
	//   * in a condition, it is only used when neither "tag" nor a source output is set.
	//   * in a target, its pattern is used as the tag name instead of the source output.
	//
	VersionFilter version.Filter `yaml:",omitempty"`
	// "age" defines the minimum or maximum age of a tag to be considered valid.
	//
	// compatible:
	//   * source
	//
	// remark:
	//   * "minimum" and "maximum" accept a duration string such as "24h", "7d", "3w" or "1y".
	//   * the age of a tag is the date of the commit it points to.
	//   * when the age filter discards every tag, the source is skipped.
	//   * "age" cannot be used when "lsremote" is true, as ls-remote lists tags without their dates.
	//
	// example:
	// ```
	//   age:
	//     minimum: 7d
	// ```
	//
	Age age.Spec `yaml:",omitempty"`
	// "tag" defines the Git tag that must exist.
	//
	// compatible:
	//   * condition
	//
	// default:
	//   the output of the associated source.
	//
	// remark:
	//   * the condition checks for an exact tag match instead of using "versionfilter".
	//
	// example:
	//   * tag: v1.0.0
	//
	Tag string `yaml:",omitempty"`
	// "message" defines the message of the annotated Git tag.
	//
	// compatible:
	//   * target
	//
	// default:
	//   Generated by updatecli
	//
	Message string `yaml:",omitempty"`
	// "key" defines which attribute of the tag the source returns.
	//
	// compatible:
	//   * source
	//
	// default:
	//   name
	//
	// remark:
	//   * accepted values are "name", "hash" or empty.
	//
	// example:
	//   * key: hash
	//
	Key string `yaml:",omitempty"`
	// "url" defines the Git repository URL to use for fetching Git tags.
	//
	// compatible:
	//   * source
	//   * condition
	//   * target
	//
	// remark:
	//   * with the ssh protocol, the user must be allowed to clone the repository
	//     with their local ssh configuration.
	//   * "url" is not needed when the repository is provided by "path" or by a "scmid".
	//   * "url" overrides "path" and the working directory provided by the scm configuration.
	//   * set "lsremote" to list the tags without cloning the repository. "url" is then required.
	//
	// example:
	//   * url: git@github.com:updatecli/updatecli.git
	//   * url: https://github.com/updatecli/updatecli.git
	//
	URL string `yaml:",omitempty"`
	// "username" defines the username used with the HTTP protocol.
	//
	// compatible:
	//   * source
	//   * condition
	//   * target
	//
	Username string `yaml:",omitempty"`
	// "password" defines the password used with the HTTP protocol.
	//
	// compatible:
	//   * source
	//   * condition
	//   * target
	//
	Password string `yaml:",omitempty"`
	// "sourcebranch" defines the branch checked out before creating the Git tag.
	//
	// compatible:
	//   * target
	//
	// default:
	//   the branch of the scm configuration.
	//
	// remark:
	//   * "sourcebranch" is required when the repository is set by "url" or "path".
	//
	SourceBranch string `yaml:",omitempty"`
	// "lsremote" lists the remote tags without cloning the repository.
	//
	// compatible:
	//   * source
	//   * condition
	//
	// default:
	//   false
	//
	// remark:
	//   * "lsremote" requires "url".
	//   * "lsremote" cannot be used with "path" or "age".
	//   * tags are sorted alphabetically, like `git ls-remote --refs --tags`.
	//     The default version filter "latest" then returns the last tag in alphabetical order,
	//     so another version filter such as semver may be needed to get the expected tag.
	//
	LsRemote *bool `yaml:",omitempty"`
	// "depth" limits the number of commits fetched from the Git repository.
	//
	// compatible:
	//   * source
	//   * condition
	//   * target
	//
	// default:
	//   0, which means no limit
	//
	// remark:
	//   * Updatecli cannot find tags that are not included in the fetched commits.
	//
	Depth *int `yaml:",omitempty"`
}

// GitTag defines a resource of kind "gittag"
type GitTag struct {
	spec Spec
	// Holds both parsed version and original version (to allow retrieving metadata such as changelog)
	foundVersion version.Version
	// Holds the "valid" version.filter, that might be different than the user-specified filter (Spec.VersionFilter)
	versionFilter version.Filter
	// nativeGitHandler holds a git client implementation to manipulate git SCMs
	nativeGitHandler gitgeneric.GitHandler
	// directory defines the local path where the git repository is cloned.
	directory string
	// lsRemote indicates that the resource should only consider remote tags.
	lsRemote bool
}

// New returns a reference to a newly initialized GitTag object from a Spec
// or an error if the provided Filespec triggers a validation error.
func New(spec interface{}) (*GitTag, error) {
	newSpec := Spec{}

	err := mapstructure.Decode(spec, &newSpec)
	if err != nil {
		return nil, err
	}

	newFilter, err := newSpec.VersionFilter.Init()
	if err != nil {
		return &GitTag{}, err
	}

	// To maintain backward compatibility with existing users,
	// the lsRemote field is defaulted to false if not specified in the manifest.
	lsRemote := false
	if newSpec.LsRemote != nil {
		lsRemote = *newSpec.LsRemote
	}

	newResource := &GitTag{
		spec:             newSpec,
		versionFilter:    newFilter,
		nativeGitHandler: &gitgeneric.GoGit{},
		lsRemote:         lsRemote,
	}

	return newResource, nil
}

// Validate tests that tag struct is correctly configured
func (gt *GitTag) Validate() error {
	validationErrors := []string{}

	if gt.spec.Key != "" && gt.spec.Key != "hash" && gt.spec.Key != "name" {
		validationErrors = append(validationErrors, "The only valid values for Key are 'name', 'hash', or empty.")
	}

	if gt.spec.LsRemote != nil && *gt.spec.LsRemote {
		if gt.spec.Path != "" {
			validationErrors = append(validationErrors, "The parameter `path` cannot be used when `lsRemote` is set to true, as `lsremote` is designed to retrieve tags from the remote repository without cloning it.")
		}
		if gt.spec.URL == "" {
			validationErrors = append(validationErrors, "The parameter `url` is required when `lsRemote` is set to true, as it needs a git repository URL to retrieve tags from the remote repository without cloning it.")
		}
		if !gt.spec.Age.IsZero() {
			validationErrors = append(validationErrors, "The parameter `age` cannot be used when `lsRemote` is set to true, as `lsremote` doesn't report the date of a tag.")
		}
	}

	if err := gt.spec.Age.Validate(); err != nil {
		validationErrors = append(validationErrors, err.Error())
	}

	// Return all the validation errors if found any
	if len(validationErrors) > 0 {
		return fmt.Errorf("validation error: the provided manifest configuration has the following validation errors:\n%s", strings.Join(validationErrors, "\n\n"))
	}

	return nil
}

// Changelog returns the changelog for this resource, or an empty string if not supported
func (gt *GitTag) Changelog(from, to string) *result.Changelogs {
	return nil
}

// clone clones the git repository
func (gt *GitTag) clone() (string, error) {
	g, err := git.New(git.Spec{
		URL:      gt.spec.URL,
		Username: gt.spec.Username,
		Password: gt.spec.Password,
		Depth:    gt.spec.Depth,
	}, "")
	if err != nil {
		return "", err
	}
	return g.Clone()
}

// ReportConfig returns a new configuration object with only the necessary fields
// to identify the resource without any sensitive information
// and context specific data.
func (gt *GitTag) ReportConfig() interface{} {
	return Spec{
		Path:          gt.spec.Path,
		VersionFilter: gt.spec.VersionFilter,
		Age:           gt.spec.Age,
		Tag:           gt.spec.Tag,
		Key:           gt.spec.Key,
		URL:           redact.URL(gt.spec.URL),
		SourceBranch:  gt.spec.SourceBranch,
	}
}
