name: Upload assets to releases

on:
  release:
    types:
      - published

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0

    # https://github.com/actions/setup-go
    - name: Set up Go 1.16
      uses: actions/setup-go@v2
      with:
        go-version: 1.16
      id: go

    - name: Install GoReleaser
      uses: goreleaser/goreleaser-action@v2
      with:
        install-only: true

    - name: Show GoReleaser version
      run: goreleaser --version

    - name: Build updateCli
      run: |
        make build.all

    - name: Upload updatecli.386.exe
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: ./dist/updatecli_windows_386/updatecli.exe
        asset_name: updatecli.386.exe
        asset_content_type: application/octet-stream
    - name: Upload updatecli.amd64.exe
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: ./dist/updatecli_windows_amd64/updatecli.exe
        asset_name: updatecli.amd64.exe
        asset_content_type: application/octet-stream
    - name: Upload updatecli.darwin.amd64
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: ./dist/updatecli_darwin_amd64/updatecli
        asset_name: updatecli.darwin.amd64
        asset_content_type: application/octet-stream
    - name: Upload updatecli.linux.386
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: ./dist/updatecli_linux_386/updatecli
        asset_name: updatecli.linux.386
        asset_content_type: application/octet-stream
    - name: Upload updatecli.linux.amd64
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: ./dist/updatecli_linux_amd64/updatecli
        asset_name: updatecli.linux.amd64
        asset_content_type: application/octet-stream
