name: Test Typos
on: [pull_request]
permissions: {}
jobs:
  run:
    name: Spell Check with Typos
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout Actions Repository
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
      - name: Check spelling of file.txt
        uses: crate-ci/typos@a67079b4ae32e18c3f53d75368c52ce53b5fb56b # master
