---
name: Updatecli
on:
  release:
  workflow_dispatch:
  schedule:
    - cron: 0 12 */14 * *
permissions: {}
jobs:
  updatecli:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: "actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd" # v6.0.2
        with:
          persist-credentials: false
      - name: "Setup updatecli"
        uses: "updatecli/updatecli-action@af341a800cdbcde3ddcebb7a62410ac06a78a207" # v3.1.2
        with:
          version: "v0.116.3"
      - name: "Set up Go"
        uses: "actions/setup-go@4a3601121dd01d1626a1e23e37211e3254c1c06c" # v6.4.0
        with:
          go-version-file: "go.mod"
        id: go
      - name: "Run updatecli"
        run: updatecli compose apply --clean-git-branches=true --experimental
        env:
          UPDATECLI_GITHUB_APP_CLIENT_ID: ${{ secrets.UPDATECLIBOT_APP_ID }}
          UPDATECLI_GITHUB_APP_PRIVATE_KEY: ${{ secrets.UPDATECLIBOT_APP_PRIVKEY }}
          UPDATECLI_GITHUB_APP_INSTALLATION_ID: ${{ secrets.UPDATECLIBOT_APP_INSTALLATION_ID }}
          UPDATECLI_UDASH_API_URL: ${{ secrets.UPDATECLI_UDASH_API_URL }}
          UPDATECLI_UDASH_ACCESS_TOKEN: ${{ secrets.UPDATECLI_UDASH_ACCESS_TOKEN }}
          UPDATECLI_UDASH_URL: ${{ secrets.UPDATECLI_UDASH_URL }}
