name: Updatecli Test
on:
  pull_request:
permissions:
  contents: read
jobs:
  updatecli:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: "actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd" # v6.0.2
      - name: "Setup updatecli"
        uses: "updatecli/updatecli-action@2cc8e6d8e356d76b0280cdd03766c36596a0614e" # v3.0.0
        with:
          version: "v0.114.0"
      - name: "Set up Go"
        uses: "actions/setup-go@4dc6199c7b1a012772edbd06daecab0f50c9053c" # v6.1.0
        with:
          go-version-file: "go.mod"
        id: go
      - name: "Test updatecli in dry-run mode"
        run: "updatecli compose diff"
        env:
          # This step is executed in untrusted context. We use a GitHub token with minimal permissions.
          UPDATECLI_GITHUB_USERNAME: ${{ github.actor }}
          UPDATECLI_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
