---
name: Updatecli Test
on:
  pull_request:
permissions:
  contents: read
jobs:
  updatecli:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: "actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1" # v7.0.1
        with:
          persist-credentials: false
      - name: "Setup updatecli"
        uses: "updatecli/updatecli-action@41b9c8d707830a9daebaeaa84c1b62d60b779564" # v3.6.0
        with:
          version: "v0.120.1"
      - name: "Set up Go"
        uses: "actions/setup-go@b7ad1dad31e06c5925ef5d2fc7ad053ef454303e" # v7.0.0
        with:
          go-version-file: "go.mod"
          cache: false
        id: go
      - name: "Test updatecli in dry-run mode"
        run: "updatecli compose diff"
        env:
          # This step is executed in untrusted context. We use a token with minimal permissions.
          UPDATECLI_GITHUB_USERNAME: ${{ github.actor }}
          UPDATECLI_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
